#!/bin/sh -e
# Copyright 2021 Canonical Ltd.
# Licensed under the GPLv3, see LICENSE file for details.

if [ -z "$VIRTUAL_ENV" -a -d venv/ ]; then
    . venv/bin/activate
fi

if [ -n "$PYTHONPATH" ]; then
    export PYTHONPATH=":$PYTHONPATH"
fi
export PYTHONPATH="src:lib$PYTHONPATH"

coverage run --source=src -m unittest -v "$@"
coverage report -m
flake8
