name: "CI"
# We don't run this workflow on 'pull_request', because we require secrets to
# upload the charm to Charmhub, and pull_request runs can't access secrets.
# PRs should be opened from a branch on the main juju/juju-controller repo,
# not from a fork.
on:
  push:
  workflow_dispatch:
env:
  CHARM_NAME: ${{ vars.CHARM_NAME }}

jobs:

  unit-tests:
    name: Unit tests
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1  # v7.0.1

    - name: Set up Python
      uses: actions/setup-python@5fda3b95a4ea91299a34e894583c3862153e4b97  # v7.0.0
      with:
        python-version: '3.10'

    - name: Install uv
      uses: astral-sh/setup-uv@20cfd1bf945f4377ade1205e4dbc17946fc9a30d # v10.0.1

    - name: Install dependencies for testing
      run: |
        uv sync --frozen --extra dev

    - name: Run tests
      run: |
        source .venv/bin/activate
        ./run_tests

  build:
    name: Build charm
    needs: unit-tests
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1  # v7.0.1

      - name: Set up Python
        uses: actions/setup-python@5fda3b95a4ea91299a34e894583c3862153e4b97  # v7.0.0
        with:
          python-version: '3.10'

      - name: Install uv
        uses: astral-sh/setup-uv@20cfd1bf945f4377ade1205e4dbc17946fc9a30d # v10.0.1

      - name: Set up LXD
        uses: canonical/setup-lxd@8c6a87bfb56aa48f3fb9b830baa18562d8bfd4ee  # 1.0.0

      - name: Add runner to lxd group
        run: |
          sudo usermod -a -G lxd $USER
          newgrp lxd

      - name: Install charmcraft
        # We use latest because there's no 4.x track yet.
        run: sudo snap install charmcraft --classic --channel=latest/stable

      - name: Pack charm
        run: sg lxd -c "charmcraft pack"

      - name: Upload charm artifact
        uses: actions/upload-artifact@043fb46d1a93c77aae656e7c1c64a875d1fc6a0a  # v7.0.1
        with:
          name: charm
          path: "*.charm"

  channel:
    name: Select Charmhub channel
    runs-on: ubuntu-latest
    outputs:
      test: ${{ steps.channel.outputs.test }}
      release: ${{ steps.channel.outputs.release }}

    steps:
    - name: Select Charmhub channel
      id: channel
      shell: bash
      run: |
        set -eux
        case ${{ github.ref_name }} in
          3.* | 4.*)
            TRACK=$(echo "${{ github.ref_name }}" | awk -F "-" '{print $1}')
            DO_RELEASE=true
            ;;
          main)
            TRACK="latest"
            DO_RELEASE=true
            ;;
          *)
            TRACK="latest"
            DO_RELEASE=false  # Don't release feature branches
            ;;
        esac

        # Feature branches will be released to the 'latest' track, so we need
        # to include the branch name to disambiguate.
        BRANCH="${{ github.ref_name }}-${{ github.sha }}"

        echo "test=$TRACK/edge/$BRANCH" >> "$GITHUB_OUTPUT"
        if [[ "$DO_RELEASE" == 'true' ]]; then
          echo "release=$TRACK/edge" >> "$GITHUB_OUTPUT"
        fi


  upload:
    name: Upload to Charmhub
    needs: [build, channel]
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1  # v7.0.1

      - name: Download packed charm
        id: download
        uses: actions/download-artifact@3e5f45b2cfb9172054b4087a40e8e0b5a5461e7c  # v8.0.1
        with:
          name: charm

      - name: Upload charms to Charmhub
        env:
          CHARMCRAFT_AUTH: ${{ secrets.CHARMCRAFT_AUTH }}
        run: |
          # We use latest because there's no 4.x track yet.
          sudo snap install charmcraft --channel latest/stable --classic
          for FILE in *.charm; do
            echo "Uploading: $FILE"
            charmcraft upload --name "$CHARM_NAME" --release "${{ needs.channel.outputs.test }}" "$FILE" 
          done


  integration:
    name: Integration tests (${{ matrix.test_name }})
    runs-on: ubuntu-latest
    needs: [build, upload, channel]
    strategy:
      fail-fast: false
      matrix:
        include:
          - test_name: lxd-22.04
            cloud: lxd
            bootstrap_base: ubuntu@22.04
          - test_name: lxd-24.04
            cloud: lxd
            bootstrap_base: ubuntu@24.04
          - test_name: lxd-26.04
            cloud: lxd
            bootstrap_base: ubuntu@26.04
          - test_name: microk8s
            cloud: microk8s

    steps:
    - name: Save charmcraft logs as artifact
      if: always() && steps.charmcraft.outcome != 'skipped'
      uses: actions/upload-artifact@043fb46d1a93c77aae656e7c1c64a875d1fc6a0a  # v7.0.1
      with:
        name: charmcraft-upload-logs-${{ matrix.test_name }}
        path: ~/.local/state/charmcraft/log/
      continue-on-error: true

    - name: Setup LXD
      if: matrix.cloud == 'lxd'
      uses: canonical/setup-lxd@8c6a87bfb56aa48f3fb9b830baa18562d8bfd4ee  # 1.0.0

    - name: Set up MicroK8s
      if: matrix.cloud == 'microk8s'
      uses: balchua/microk8s-actions@65ff1f88f8ecd153879a9b6955659f3144b27714  # 0.4.2
      with:
        channel: "1.36-strict/stable"
        addons: '["dns", "hostpath-storage"]'

    - name: Install Juju
      run: |
        sudo snap install juju --channel 4.1/stable

    - name: Bootstrap on LXD
      if: matrix.cloud == 'lxd'
      run: |
        juju bootstrap lxd c \
          --bootstrap-base=${{ matrix.bootstrap_base }} \
          --controller-charm-channel=${{ needs.channel.outputs.test }}

    - name: Bootstrap on MicroK8s
      if: matrix.cloud == 'microk8s'
      run: |
        sg snap_microk8s <<EOF
          juju bootstrap microk8s c \
            --controller-charm-channel=${{ needs.channel.outputs.test }}
        EOF

    - name: Check charm status
      run: |
        juju switch controller
        juju status

        start_time="$(date -u +%s)"
        until [[ $(juju status --format=json 2>/dev/null | jq -r '.applications.controller["application-status"].current') == "active" ]]; do
          echo "Waiting for controller to become active..."
          juju status
          sleep 10

          elapsed=$(( $(date -u +%s) - start_time ))
          if [[ ${elapsed} -ge 600 ]]; then
            echo "Timed out waiting for controller to become active"
            juju status
            exit 1
          fi
        done

    - name: Get some info for debugging
      if: failure()
      run: |
        set -x
        set +e
        juju status -m controller
        juju debug-log -m controller --replay
        sg snap_microk8s <<EOF
          microk8s.kubectl -n controller-c get all
          microk8s.kubectl -n controller-c get -o yaml pod/controller-0
        EOF

    # TODO: test integration with dashboard / ha-proxy
